
  # After registering a name on build.snapcraft.io, commit an uncommented line:
  name: rphoto
  version: '0.4.5' 
  base: core18
  summary: easy handling of digital camera's photos.
  description: |
    RPhoto is a small software aiming at the easy handling of digital camera's photos. (RPhoto 
    is the next generation of IMPhoto). Its origin resides in the lack of a simple software 
    capable of cropping photos with a constant ratio, to avoid white borders when printing.

  icon: resources/FilesPhoto.png
#  license: GPL
  
  grade: stable # must be 'stable' to release into candidate/stable channels
#  confinement: classic # use 'strict' once you have the right plugs and slots
  confinement: strict

  apps:
    rphoto:
      desktop: /usr/local/share/applications/rphoto.desktop
      command: desktop-launch $SNAP/bin/RPhoto
      extensions: [gnome-3-28]
      plugs: [home, desktop, desktop-legacy, unity7, x11, wayland, gsettings]

  parts:
    rphoto:
      plugin: autotools
      override-build: autoreconf && ./configure && make && make install
      source: https://github.com/rpeyron/rphoto.git
      stage-packages:
      - libwxgtk3.0-gtk3-0v5
      - libexif12
      - libjpeg-progs
      - jhead
      - libatk-adaptor
      - libgail-common
      build-packages:
      - libexif-dev
      - libwxgtk3.0-gtk3-dev
      - libjpeg8-dev
      - zip
      - libtool
      - pkg-config
      - autoconf
      - automake
      - autopoint
          
