
  # After registering a name on build.snapcraft.io, commit an uncommented line:
  name: rphoto
  version: '0.4.5' 
  base: core18
  summary: easy handling of digital camera's photos.
  description: |
    RPhoto is a small software aiming at the easy handling of digital camera's photos. (RPhoto 
    is the next generation of IMPhoto). Its origin resides in the lack of a simple software 
    capable of cropping photos with a constant ratio, to avoid white borders when printing.

  icon: resources/FilesPhoto.png
#  license: GPL
  
  grade: stable # must be 'stable' to release into candidate/stable channels
#  confinement: classic # use 'strict' once you have the right plugs and slots
  confinement: strict

  apps:
    rphoto:
      desktop: share/applications/rphoto.desktop
      command: desktop-launch $SNAP/bin/RPhoto
      plugs: [home, desktop, desktop-legacy, unity7, x11, wayland, gsettings]

  parts:
    rphoto:
      # See 'snapcraft plugins'
      after: [desktop-gtk3]      
      plugin: autotools
      override-build: autoreconf && ./configure && make && make install
      source: https://github.com/rpeyron/rphoto.git
      stage-packages:
      - libwxgtk3.0-gtk3-0v5
      - libexif12
      - libjpeg-progs
      - jhead
      - libatk-adaptor
      - libgail-common
      build-packages:
      - libexif-dev
      - libwxgtk3.0-gtk3-dev
      - libjpeg8-dev
      - zip
      - libtool
      - pkg-config
      - autoconf
      - automake
      - autopoint
          
    desktop-gtk3:
      build-packages:
      - build-essential
      - libgtk-3-dev
      make-parameters:
      - FLAVOR=gtk3
      plugin: make
      source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
      source-subdir: gtk
      stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk-3-bin
      - unity-gtk3-module
      - libappindicator3-1
      - locales-all
      - xdg-user-dirs
      - ibus-gtk3
      - libibus-1.0-5
      - fcitx-frontend-gtk3  
